const LOG_EVENTS = Object.freeze({
  SERVER_STARTED: 'SERVER_STARTED',
  SERVER_SHUTDOWN: 'SERVER_SHUTDOWN',

  AUTH_SIGNUP: 'AUTH_SIGNUP',
  AUTH_LOGIN: 'AUTH_LOGIN',
  AUTH_LOGOUT: 'AUTH_LOGOUT',
  AUTH_VERIFICATION: 'AUTH_VERIFICATION',
  AUTH_FAILURE: 'AUTH_FAILURE',

  BOOKING_CREATED: 'BOOKING_CREATED',
  BOOKING_UPDATED: 'BOOKING_UPDATED',
  BOOKING_CANCELLED: 'BOOKING_CANCELLED',
  BOOKING_FAILED: 'BOOKING_FAILED',

  PAYMENT_CREATED: 'PAYMENT_CREATED',
  PAYMENT_SUCCESS: 'PAYMENT_SUCCESS',
  PAYMENT_FAILED: 'PAYMENT_FAILED',

  WEBHOOK_RECEIVED: 'WEBHOOK_RECEIVED',
  WEBHOOK_PROCESSED: 'WEBHOOK_PROCESSED',
  WEBHOOK_DUPLICATE: 'WEBHOOK_DUPLICATE',
  WEBHOOK_FAILED: 'WEBHOOK_FAILED',

  ADMIN_ACTION: 'ADMIN_ACTION',

  VALIDATION_ERROR: 'VALIDATION_ERROR',
  AUTHORIZATION_ERROR: 'AUTHORIZATION_ERROR',
  NOT_FOUND_ERROR: 'NOT_FOUND_ERROR',

  INTERNAL_ERROR: 'INTERNAL_ERROR',
});

module.exports = LOG_EVENTS;